name: starter_firebase_auth
description: "Starter Firebase Auth"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
#  flutter_flavorizr: ^2.2.3
  flutter_flavorizr:
    git:
      url: https://github.com/wjlee611/flutter_flavorizr.git
      # ref: feat/migrate-3-29
      ref: chore/temp-migrate-3-29
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
